FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    gcc \
    libc-dev \
    librdkafka-dev

COPY requirements.txt /
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/

CMD uvicorn --host 0.0.0.0 --port 8080 src.main:app --reload